---
  dataSource: "issues"
  prefix: ""
  ignore-tags-with: "fuse"
  onlyMilestones: false
  groupBy: {
    "Enhancements": ["cat/enhancement", "cat/feature"],
    "Bug Fixes": ["cat/bug"],
    "Design": ["cat/design"],
    "Misc": ["cat/build", "cat/process", "cat/techdebt", "cat/techdoc"]
  }
  ignore-issues-with: [
    "wontfix", "status/stale", "dependencies", "cat/question"
  ]
  "template": {
        "issue": "- [{{text}}]({{url}}) {{name}}"
  }
  changelogFilename: "CHANGELOG.md"
